### ISSUE TITLE
Missing parameter:`resourceItem in resource with a delete button in activeActions if the table has an entry with an id equal to 0.

### ISSUE THREAD

**Issue by carma100** [moonshine-software/moonshine#779]
### MoonShine Version

2.6.8

### Laravel Version

10.41.0

### PHP Version

8.2

### Database Driver & Version

mariadb:10.11

### Description

I've got an issue: `Missing required parameter for [Route: moonshine.crud.destroy] [URI: admin/resource/{resourceUri}/crud/{resourceItem}] [Missing parameter: resourceItem].` 'cause I put into the table `partners` an id with a value equal to 0, and in the resource, I'm used `getActiveActions` with the `delete` button. Looks like somewhere 0 is implemented as `false`.
![issue wih 0](https://github.com/moonshine-software/moonshine/assets/73887319/23e6e564-9923-4c86-badb-42d896956883)

I can already hear the expressions: "Why are you using id=0?" - but believe me, sometimes you have to do something like this, especially when you are setting up Moonshine on legacy projects.

I hope I helped you a little.

### Steps To Reproduce

Make any model, resource, and put an element with a 0 id into a table, for example, `articles`. In the resource, write the function `getActiveActions()` with a `delete` button. All of these steps should help you catch the issue.
![getActiveActions with delete button](https://github.com/moonshine-software/moonshine/assets/73887319/e210f608-01f9-4529-bee6-6e643f0e2c05)
![An element in db with id equal 0](https://github.com/moonshine-software/moonshine/assets/73887319/d1ea239d-2d67-4cec-ab30-0fcd6fef98d6)

**Comment by lee-to** [comment]
Fixed

**Comment by carma100** [comment]
Hi there! 
The problem still persists `Missing the required parameter for [Route: moonshine.crud.destroy] [URI: admin/resource/{resourceUri}/crud/{ResourceItem}] [The parameter: ResourceItem] is missing`, if in my table, for example, partners, I have element 0 in the table and there is a delete button in the `getActiveACtions()` function, but if you will remove `delete` button from `getActiveActions` all will be fine. Maybe all these things don't make any sense, because I can use the `query` function to get items whose ID is greater than 0.

**Comment by lee-to** [comment]
> Hi there! The problem still persists `Missing the required parameter for [Route: moonshine.crud.destroy] [URI: admin/resource/{resourceUri}/crud/{ResourceItem}] [The parameter: ResourceItem] is missing`, if in my table, for example, partners, I have element 0 in the table and there is a delete button in the `getActiveACtions()` function, but if you will remove `delete` button from `getActiveActions` all will be fine. Maybe all these things don't make any sense, because I can use the `query` function to get items whose ID is greater than 0.

Update to 2.7.1
